package view;

import data.Usuario;
import data.UsuarioDao;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mathe
 */
public class Entrar extends javax.swing.JFrame {
    
static String senhaBD, nomeBD, idadeBD;
    /**
     * Creates new form entrar
     * 
     * 
     */


    
    public Entrar() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcessar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JFormattedTextField();
        btnVoltar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENTRAR");
        setResizable(false);
        getContentPane().setLayout(null);

        btnAcessar.setText("acessar");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcessar);
        btnAcessar.setBounds(280, 230, 90, 40);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(80, 100, 210, 30);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(80, 40, 210, 30);

        lblSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblSenha.setText(" Senha:");
        lblSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 100, 50, 30);

        lblEmail.setEditable(false);
        lblEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblEmail.setText(" E-mail:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(20, 40, 50, 30);

        btnVoltar.setText("voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(60, 230, 90, 40);

        lblFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathe\\Downloads\\Fundo.png")); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(-6, -6, 410, 310);

        setSize(new java.awt.Dimension(408, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSenhaActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        String email;
        email = txtEmail.getText();
        String senha = txtSenha.getText();

        //salva as informações digitadas no campo
if(email.equals("") || senha.equals("")){
    JOptionPane.showMessageDialog(null, "digite alguma infomação");
}else{
        UsuarioDao dao = new UsuarioDao();
        boolean status = dao.conectar();
        //verifica se foi feita a coxeção
        if(status==true){
            Usuario usuario = dao.consultar(email);
            //se foi feita tras as informações do banco para a classe usuario
            if(usuario==null){
                //mesagem que vai aparecer caso não teha sido digitado nada 
                JOptionPane.showMessageDialog(null, "usuario não encontrado");
            }else{
                
                nomeBD = usuario.getNome();
                idadeBD = usuario.getIdade();
                senhaBD = usuario.getSenha();
                
                
                
                //apos as consultas os dados são salvos em variaveis locais                
            

            if(senha.equals(senhaBD)){
                //criar uma comparação da senha digitada no campo com a que foi cadastrada
                
                //caso seja igual será concedido acesso
                JOptionPane.showMessageDialog(null,"Acesso permitido");
                new Pagina(nomeBD,idadeBD).setVisible(true);
                dispose();

            }else{
                //se a senha não for igual aparecerá uma mensagem de erro
                JOptionPane.showMessageDialog(null, "senha incorreta");
            }
            dao.desconectar();
            }
        }else if(status==false){
            //mensagem que mostra erro
            JOptionPane.showMessageDialog(null,"erro de conexação");
        }
        
        
}
    }//GEN-LAST:event_btnAcessarActionPerformed

    

  

    

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
new Inicio().setVisible(true); 
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Entrar().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField lblEmail;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JFormattedTextField lblSenha;
    public javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

  

        
}
