package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mathe
 */

import javax.swing.JOptionPane;
public class Equaçao_2_grau extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Equaçao_2_grau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRaizes = new javax.swing.JButton();
        a = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtC = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtRa = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtB = new javax.swing.JTextPane();
        lblTitulo = new javax.swing.JFormattedTextField();
        lblEquaçao = new javax.swing.JFormattedTextField();
        lblRegra = new javax.swing.JFormattedTextField();
        lblA = new javax.swing.JFormattedTextField();
        lblB = new javax.swing.JFormattedTextField();
        lblC = new javax.swing.JFormattedTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EQUAÇÃO DO 2 GRAU");
        setResizable(false);
        getContentPane().setLayout(null);

        btnRaizes.setText("achar raizes");
        btnRaizes.setToolTipText("");
        btnRaizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRaizes);
        btnRaizes.setBounds(60, 230, 100, 50);

        a.setViewportView(txtA);

        getContentPane().add(a);
        a.setBounds(110, 90, 100, 30);

        jScrollPane5.setViewportView(txtC);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(110, 180, 100, 30);

        txtRa.setEditable(false);
        jScrollPane6.setViewportView(txtRa);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(222, 230, 150, 57);

        jScrollPane4.setViewportView(txtB);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(110, 133, 100, 30);

        lblTitulo.setEditable(false);
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblTitulo.setText("Equação do 2 grau");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(90, 10, 120, 20);

        lblEquaçao.setEditable(false);
        lblEquaçao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblEquaçao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblEquaçao.setText("[a]X^2 + [b]X + [c] = 0");
        getContentPane().add(lblEquaçao);
        lblEquaçao.setBounds(10, 36, 140, 18);

        lblRegra.setEditable(false);
        lblRegra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblRegra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblRegra.setText(" Se valor for neutro coloque 0");
        getContentPane().add(lblRegra);
        lblRegra.setBounds(80, 61, 170, 20);

        lblA.setEditable(false);
        lblA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblA.setText(" valor de a:");
        getContentPane().add(lblA);
        lblA.setBounds(28, 90, 70, 26);

        lblB.setEditable(false);
        lblB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblB.setText(" valor de b:");
        getContentPane().add(lblB);
        lblB.setBounds(30, 140, 70, 23);

        lblC.setEditable(false);
        lblC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblC.setText(" valor de c:");
        getContentPane().add(lblC);
        lblC.setBounds(30, 190, 70, 23);

        lblFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathe\\Downloads\\Fundo.png")); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(-6, -10, 400, 320);

        setSize(new java.awt.Dimension(409, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizesActionPerformed
        
        
        double A,B,C;
	double d; //delta
	double x1,x2;
	double r; //radiação
	double v1,v2,v3;//raizes de equaçao imcompleta
        
        A = Double.parseDouble(txtA.getText());
        B = Double.parseDouble(txtB.getText());
        C = Double.parseDouble(txtC.getText());
       
           
        
                    //comando que mostra erro
                if(A==0 && B==0 && C==0){
                JOptionPane.showMessageDialog(null, "erro coloque ao menos uma variavel diferente de 0");
                }
        
                                    if(A==0){
				        v1 = - C / B;
                                        txtRa.setText(String.valueOf(v1));
				       // System.out.println(v1);
				    }
				    
				    if(B==0){
				        v2 = Math.sqrt(-C/A);
                                        txtRa.setText(String.valueOf(v2));
				      //  System.out.println(v2);
				    }
				     if(C==0){
				       // System.out.println("o valor da primera raiz e: 0");
				        v3 = -B/A;
				  //      System.out.println("o valor da segunda raiz e: " + v3);
                                  txtRa.setText("x1 : 0 \nx2:  " + String.valueOf(v3) );
                                  
				    }
				    
				    
				   if(B==0 && C==0){
				   // System.out.println("o valor da raiz e igual a 0");
                                   txtRa.setText("0");
                                    }
                                  else if (A!=0 && B!=0 && C!=0){
				d = Math.pow(B,2) - 4*A*C; //calcular o delta
				r = Math.sqrt(d); //raiz quadrada do delta
				 
				x1 = (- B + r) / (2*A);
				x2 = (- B - r) / (2*A);
				txtRa.setText("x1: " + String.valueOf(x1) + "\nx2: " + String.valueOf(x2));
                                
		//System.out.println("a primeira raiz e: " + x1);
		//System.out.println("a segunda raiz e: " + x2);
				}   
    }//GEN-LAST:event_btnRaizesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equaçao_2_grau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equaçao_2_grau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equaçao_2_grau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equaçao_2_grau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Equaçao_2_grau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane a;
    private javax.swing.JButton btnRaizes;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JFormattedTextField lblA;
    private javax.swing.JFormattedTextField lblB;
    private javax.swing.JFormattedTextField lblC;
    private javax.swing.JFormattedTextField lblEquaçao;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JFormattedTextField lblRegra;
    private javax.swing.JFormattedTextField lblTitulo;
    private javax.swing.JTextPane txtA;
    private javax.swing.JTextPane txtB;
    private javax.swing.JTextPane txtC;
    private javax.swing.JTextPane txtRa;
    // End of variables declaration//GEN-END:variables
}
