package view;


import javax.swing.JOptionPane;

public class Pagina extends javax.swing.JFrame {
    String n,i;
    
        
 
    /**
     * Creates new form pagina
     */
    public Pagina() {
        initComponents();
    }
    
     public Pagina(String nome, String idade) {
        initComponents();
  
        lblTitulo.setText("seja bem vindo " + nome);
        lblsubTitulo.setText(idade + " anos");
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAvancar = new javax.swing.JButton();
        ComboEscolha = new javax.swing.JComboBox<>();
        lblAssunto = new javax.swing.JFormattedTextField();
        lblTitulo = new javax.swing.JFormattedTextField();
        lblsubTitulo = new javax.swing.JFormattedTextField();
        lblFundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jmAtendimento = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();
        jmExcluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAGINA PRICIPAL");
        setResizable(false);
        getContentPane().setLayout(null);

        btnAvancar.setText("avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar);
        btnAvancar.setBounds(270, 220, 100, 30);

        ComboEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Matriz", "Equação do segundo grau" }));
        getContentPane().add(ComboEscolha);
        ComboEscolha.setBounds(160, 130, 160, 30);

        lblAssunto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblAssunto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblAssunto.setText(" Escolha o assunto");
        getContentPane().add(lblAssunto);
        lblAssunto.setBounds(10, 130, 120, 30);

        lblTitulo.setEditable(false);
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTituloActionPerformed(evt);
            }
        });
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(10, 30, 180, 30);

        lblsubTitulo.setEditable(false);
        lblsubTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblsubTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(lblsubTitulo);
        lblsubTitulo.setBounds(10, 70, 100, 30);

        lblFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mathe\\Downloads\\Fundo.png")); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, -20, 400, 300);

        menu.setText("conta");

        jmAtendimento.setText("Atendimeto");
        jmAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAtendimentoActionPerformed(evt);
            }
        });
        menu.add(jmAtendimento);

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        menu.add(jmSair);

        jmExcluir.setText("Excuir conta");
        jmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExcluirActionPerformed(evt);
            }
        });
        menu.add(jmExcluir);

        jMenuBar2.add(menu);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(416, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
 String escolha =  ComboEscolha.getSelectedItem().toString();

    if(escolha.equals("Matriz")){
        new Matriz().setVisible(true);
        
    }else if(escolha.equals("Equação do segundo grau")){
        new Equaçao_2_grau().setVisible(true);
        
    }else{
        JOptionPane.showMessageDialog(null,"Digite uma opção");
    }

    }//GEN-LAST:event_btnAvancarActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
new Inicio().setVisible(true);  
dispose();              // TODO add your handling code here:
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExcluirActionPerformed
new Excluir().setVisible(true);  
dispose();
   // TODO add your handling code here:
    }//GEN-LAST:event_jmExcluirActionPerformed

    private void lblTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloActionPerformed

    private void jmAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAtendimentoActionPerformed
new Sac().setVisible(true);  
          // TODO add your handling code here:
    }//GEN-LAST:event_jmAtendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Pagina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEscolha;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmAtendimento;
    private javax.swing.JMenuItem jmExcluir;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JFormattedTextField lblAssunto;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JFormattedTextField lblTitulo;
    private javax.swing.JFormattedTextField lblsubTitulo;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables

    
}
